### ISSUE TITLE
加Graphql的好处在哪？

### ISSUE THREAD

**Issue by shengqiang025210** [AutoGraphQL/AutoGraphQL#2]
@TommyLemon  请问apijson加Graphql的好处是什么？没有想明白，请求思路是前端发送请求到graphql，然后apijson解析json生成sql查询结果返回给graphql然后再返回给前端是这个思路是吗？

**Comment by TommyLemon** [comment]
主要是 Facebook 的影响力很大，号召力很强。
其次是整合 API 及其它服务确实比 APIJSON 的远程函数直观一些。

**Comment by TommyLemon** [comment]
很无奈，有时候看 GraphQL 要冷下去了，还得帮它推广、解决群友关于 GraphQL 的问题，
它火起来能对 APIJSON 火起来有帮助，毕竟大家都信任 Facebook，有大厂背书推广起来要容易很多

**Comment by shengqiang025210** [comment]
树大好乘凉，树越大影响力越大，有些事做起来更容易，apijson还是很棒的，看了你们的智慧就越觉得精彩，做东西这过程中的要付出的可不是一般的辛苦，希望好东西能越来越强一直延续下去。

**Comment by shengqiang025210** [comment]
能加我qq：2403498061或者微信：17612172169嘛？apijson公布的群好像没搜到，公司想用apijson，想请教你几个问题.

**Comment by TommyLemon** [comment]
是的，感谢理解和支持

**Comment by TommyLemon** [comment]
最近QQ服务器应该出问题了，我的几个群，还有其它作者的群都搜不到，难怪最近没人加群

**Comment by TommyLemon** [comment]
已加 QQ
