### ISSUE TITLE
使用新版本的APIJSON报错。

### ISSUE THREAD

**Issue by gemufeng** [AutoGraphQL/AutoGraphQL#3]
我在pom中导入了新的apijson版本：
<dependency>
	<groupId>com.github.APIJSON</groupId>
	<artifactId>apijson-framework</artifactId>
	<version>5.1.0</version>
</dependency>，但是报错，错误信息如下：
{
    "errors": [
        {
            "message": "Validation error of type SubSelectionNotAllowed: Sub selection not allowed on leaf type String of field fetch @ 'fetch'",
            "locations": [
                {
                    "line": 2,
                    "column": 3
                }
            ],
            "extensions": {
                "classification": "ValidationError"
            }
        },
        {
            "message": "Validation error of type WrongType: argument 'arg' with value 'ObjectValue{objectFields=[ObjectField{name='Book', value=ObjectValue{objectFields=[ObjectField{name='id', value=IntValue{value=4}}]}}]}' is not a valid 'String' - Expected AST type 'StringValue' but was 'ObjectValue'. @ 'fetch'",
            "locations": [
                {
                    "line": 2,
                    "column": 9
                }
            ],
            "extensions": {
                "classification": "ValidationError"
            }
        }
    ]
}

请问我应该如何解决？

**Comment by TommyLemon** [comment]
具体请求参数发下

**Comment by gemufeng** [comment]
> 具体请求参数发下
```graphql
{
  fetch(arg: {
    Book: {
      id: 4
    }
  }) {
    data
  }
}
```

**Comment by TommyLemon** [comment]
arg 类型 改为 字符串 
```graphql
{
  fetch(arg: `{
    Book: {
      id: 4
    }
  }`) {
    data
  }
}
```

试试

**Comment by gemufeng** [comment]
> 

还是不行。
{
    "errors": [
        {
            "message": "Invalid Syntax : token recognition error at: '`' at line 2 column 14",
            "locations": [
                {
                    "line": 2,
                    "column": 14
                }
            ],
            "extensions": {
                "classification": "InvalidSyntax"
            }
        }
    ]
}

**Comment by TommyLemon** [comment]
看来你用的 GraphQL 客户端不支持内部有多行字符串（反引号包裹），改为常规的字符串试试

```graphql
{
  fetch(arg: "{'Book':{'id':4}}") {
    data
  }
}
```

这样应该也行，fastjson 支持符合变量命名的 key 不带引号
```graphql
{
  fetch(arg: "{Book:{id:4}}") {
    data
  }
}
```

https://github.com/AutoGraphQL/AutoGraphQL/blob/master/src/main/java/graphql/examples/springboot/GraphQLController.java#L37-L78

**Comment by gemufeng** [comment]
我用的postman客户端做的测试，请问一般需要用什么客户端来测试接口？
<img width="858" alt="Screen Shot 2022-06-07 at 4 56 05 PM" src="https://user-images.githubusercontent.com/42954433/172340108-a66a1eaa-f1e9-4caf-b06c-0c5ad73b8c6a.png">

**Comment by TommyLemon** [comment]
[GraphAuto](https://github.com/AutoGraphQL/GraphAuto) 或 GraphiQL。
不过 Postman 也是可以的，只是 arg 值格式要改成上面说的传字符串


> 看来你用的 GraphQL 客户端不支持内部有多行字符串（反引号包裹），改为常规的字符串试试
> 
> ```graphql
> {
>   fetch(arg: "{'Book':{'id':4}}") {
>     data
>   }
> }
> ```
> 
> 这样应该也行，fastjson 支持符合变量命名的 key 不带引号
> 
> ```graphql
> {
>   fetch(arg: "{Book:{id:4}}") {
>     data
>   }
> }
> ```
> 
> https://github.com/AutoGraphQL/AutoGraphQL/blob/master/src/main/java/graphql/examples/springboot/GraphQLController.java#L37-L78

后面看下是否引入 graphql-java 的 JSON 类型，方便直接传参

**Comment by gemufeng** [comment]
多谢指点，已经可以获取数据了。

**Comment by TommyLemon** [comment]
@gemufeng  更新了代码和文档，当所有 key 符合变量命名时，可以直接用 JSON 对象了，且 key 不加引号。
https://github.com/AutoGraphQL/AutoGraphQL

![image](https://user-images.githubusercontent.com/5738175/172898753-6651e8a0-f81d-42a1-9912-192268e8dd9e.png)
![image](https://user-images.githubusercontent.com/5738175/172898894-fc9cb94d-7a06-4eb4-a3d5-70eafa4a2430.png)

**Comment by gemufeng** [comment]
非常感谢帮忙，你们的项目给我们的产品带来了巨大的好处，我们需要深度的使用apijson，非常感谢。

**Comment by TommyLemon** [comment]
还有个配套的工具，用 GraphQL 变量名传参 $arg，就对 JSON 内 key 格式没要求了
https://github.com/AutoGraphQL/GraphAuto
